spring:
 application:
  name: Accounts
 profiles:
  active: dev 
  
#cloud config server configuration
 config:
  import: "configserver:http://localhost:8071/"  
 datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa
  password: ''
 h2:
  console:
   enabled: true
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
   ddl-auto: update
  show-sql: true

#rabbitmq configuration
 rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest" 
    
server:
 port: 9595

#spring boot actuator configuration 
management:
  endpoints:
   web:
    exposure:
     include: "*" 
   